-- 테스트 코칭 세션 데이터 삽입
INSERT OR REPLACE INTO coaching_sessions (
  id, planner_id, context, situation_type, analyzed_question, category, 
  key_points, coaching_point, coaching_evidence, dialogue, 
  learning_needs, action_guidelines, reference_sources,
  ai_analysis, coaching_advice, recommended_approach, tacit_knowledge_applied,
  session_date, is_shared, is_validated, use_for_learning,
  planner_feedback, effectiveness_rating, director_feedback, 
  director_rating, manager_note, manager_ai_advice, manager_request
) VALUES 
(
  2, 11, 
  '50대 근로자 나 씨가 암 진단 받아 보험금 청구했는데 보험사에서 거절함. 약관상 특정 암 종류는 포함 안 된다고 함.',
  '생활코칭',
  '고객이 암 진단 받고 보험금 청구를 거절당했어요. 어떻게 가족유지에 도움 거듭하면서도 윤리적으로 대응해야 할까요?',
  '규제',
  '1) 보험 약관의 정확한 검토 2) 고객의 감정적 어려움 공감 3) 윤리적 대응',
  '약관을 상세히 검토하고, 고객에게 명확하게 설명하되 공감과 지원을 병행해야 합니다.',
  '[금융감독원 보험분쟁 가이드], [보험약관 해석 사례]',
  '',
  '보험 약관 해석 역량, 고객 커뮤니케이션',
  '1) 약관 재검토 2) 금융감독원 상담 안내 3) 대안 상품 제안',
  '[{"title":"금융감독원 보험분쟁조정","url":"https://www.fss.or.kr"}]',
  'AI 분석: 고객 신뢰 유지와 윤리적 대응이 핵심',
  '**고객 상황 이해:**\n암 진단이라는 심각한 상황에서 보험금 거절은 고객에게 큰 충격입니다.\n\n**권장 접근법:**\n1. 약관 상세 검토 후 명확한 설명\n2. 금융감독원 분쟁조정 안내\n3. 대안 상품 또는 추가 보장 제안\n4. 지속적인 관심과 지원',
  '공감 기반 커뮤니케이션 + 전문적 조언',
  '고객의 감정을 먼저 이해하고, 전문성을 바탕으로 실질적 도움 제공',
  '2025-03-20 14:30:00',
  1, 0, 0,
  '설명이 명확해서 도움이 되었습니다.',
  4,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  4, 11,
  '고객이 연금보험 가입 후 3년 후 해지를 원함. 원금 손실이 크다고 설명했지만 당장 돈이 필요하다고 함.',
  '영업기법',
  '고객이 조기 해지를 원하는데 손실이 큽니다. 어떻게 설득해야 할까요?',
  '상품지식',
  '1) 해지 손실 명확한 설명 2) 대안 제시 (계약자 대출 등) 3) 장기 유지 시 이익',
  '해지보다는 계약자 대출이나 납입 중단 등 대안을 먼저 제시해야 합니다.',
  '[연금보험 약관], [계약자 대출 안내]',
  '',
  '상품 구조 이해, 대안 제시 능력',
  '1) 해지 시 손실 계산서 제시 2) 계약자 대출 설명 3) 납입 중단 옵션 안내',
  '[{"title":"연금보험 해지 vs 대출","url":"https://example.com"}]',
  'AI 분석: 고객의 급전 필요성과 장기 이익 균형',
  '**고객 니즈 파악:**\n고객이 당장 돈이 필요한 이유를 먼저 파악하세요.\n\n**권장 접근법:**\n1. 해지 시 예상 손실액 명확히 제시\n2. 계약자 대출 옵션 설명 (이자율, 한도 등)\n3. 납입 중단 후 유지 방안 제안\n4. 장기 유지 시 예상 수익 비교',
  '대안 제시 중심 상담',
  '해지보다 나은 선택지를 제공하여 고객과 회사 모두에게 이익이 되는 방향 제시',
  '2025-03-21 10:00:00',
  1, 0, 0,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);
